# Copyright 2020 David Garcia
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
  bind_address_subnet:
    type: string
    description: |
      The selected bind address will need to be part of this subnet.
      If this is not set, it will use the IP address from the default interface.
    default: ""
  mme_addr:
    type: string
    description: |
      This is MME address from AGW
    default: ""
  enb-name:
    type: string
    description: |
      TODO
    default: dummyENB01
  enb-mcc:
    type: string
    description: |
      TODO
    default: "722"
  enb-mnc:
    type: string
    description: |
      TODO
    default: "17"
  enb-rf-device-name:
    type: string
    description: |
      TODO
    default: "zmq"
  enb-rf-device-args:
    type: string
    description: |
      TODO
    default: fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=23.04e6
  ue-usim-algo:
    type: string
    description: |
      TODO
    default: milenage
  ue-nas-apn:
    type: string
    description: |
      TODO
    default: default
  ue-device-name:
    type: string
    description: |
      TODO
    default: zmq
  ue-device-args:
    type: string
    description: |
      TODO
    default: tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6
